blank_issues_enabled: false
contact_links:
  - name: "Join the Community Group"
    about: Join the OpenAgent community to discuss and get help from others
    url: https://github.com/mannaandpoem/OpenAgent?tab=readme-ov-file#community-group
