# Server configuration
[server]
host = "localhost"
port = 5172

# CORS settings
[server.cors]
allow_origins = ["*"]
allow_credentials = true
allow_methods = ["*"]
allow_headers = ["*"]

# API configuration
[api]
title = "OpenManus API"
version = "1.0.0"
description = "API for OpenManus - an intelligence augmentation platform"
